version: "3.4"
services:
  races:
    build: "."
    ports:
      - "3000:3000"
    restart: on-failure
    command: bash -c "chmod +x ./wait-for-it.sh && gunicorn 'flaskr:create_app()' -b 0.0.0.0:3000"
    depends_on:
      - races-db
  races-db:
    image: postgres:14.5
    ports:
      - "5432:5432"
    volumes:
      - ./docker_data:/var/lib/postgresql/data
    restart: on-failure
    environment:
      POSTGRES_DB: races
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
